import {
  CarAudiA1,
  CarAudiA5,
  CarAudiETron,
  CarAudiQ5,
  CarBmw850i,
  CarBmwM4,
  CarBmwM5,
  CarFiat500,
  CarFordMustang,
  CarLandRover,
  CarMercedesC,
  CarMercedesS,
  CarPeugeot208,
  CarPeugeot308,
  CarPeugeot508,
  CarPorsche,
  CarGolf,
} from "../images/cars-big";

export const CAR_DATA = [
  [
    {
      name: "Audi A1",
      price: "146,88",
      img: CarAudiA1,
      model: "A1 Sportback",
      mark: "Audi",
      year: "2008",
      doors: "3/4",
      air: "Oui",
      transmission: "Manuelle",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Audi A5",
      price: "178,99",
      img: CarAudiA5,
      model: "A5",
      mark: "Audi",
      year: "2012",
      doors: "4/5",
      air: "Oui",
      transmission: "Manuelle",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Audi e-tron",
      price: "299,00",
      img: CarAudiETron,
      model: "e-tron",
      mark: "Audi",
      year: "2020",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Électrique",
    },
  ],
  [
    {
      name: "Audi Q5",
      price: "219,50",
      img: CarAudiQ5,
      model: "Q5",
      mark: "Audi",
      year: "2015",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "BMW 850i",
      price: "315,75",
      img: CarBmw850i,
      model: "850i",
      mark: "BMW",
      year: "2019",
      doors: "2/3",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "BMW M4",
      price: "279,99",
      img: CarBmwM4,
      model: "M4",
      mark: "BMW",
      year: "2017",
      doors: "2/3",
      air: "Oui",
      transmission: "Manuelle",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "BMW M5",
      price: "339,00",
      img: CarBmwM5,
      model: "M5",
      mark: "BMW",
      year: "2021",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "BMW M5",
      price: "339,00",
      img: CarFiat500,
      model: "M5",
      mark: "BMW",
      year: "2021",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "Mustang",
      price: "249,99",
      img: CarFordMustang,
      model: "Mustang",
      mark: "Ford",
      year: "2020",
      doors: "2/3",
      air: "Oui",
      transmission: "Manuelle",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "Land Rover",
      price: "269,00",
      img: CarLandRover,
      model: "Range Rover Sport",
      mark: "Land Rover",
      year: "2018",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Mercedes C",
      price: "199,99",
      img: CarMercedesC,
      model: "Classe C",
      mark: "Mercedes",
      year: "2016",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Mercedes S",
      price: "389,00",
      img: CarMercedesS,
      model: "Classe S",
      mark: "Mercedes",
      year: "2020",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "Peugeot 208",
      price: "110,50",
      img: CarPeugeot208,
      model: "208",
      mark: "Peugeot",
      year: "2017",
      doors: "3/4",
      air: "Oui",
      transmission: "Manuelle",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "Peugeot 308",
      price: "155,99",
      img: CarPeugeot308,
      model: "308",
      mark: "Peugeot",
      year: "2019",
      doors: "4/5",
      air: "Oui",
      transmission: "Manuelle",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Peugeot 508",
      price: "198,00",
      img: CarPeugeot508,
      model: "508",
      mark: "Peugeot",
      year: "2020",
      doors: "4/5",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Porsche",
      price: "399,00",
      img: CarPorsche,
      model: "911 Carrera",
      mark: "Porsche",
      year: "2022",
      doors: "2/3",
      air: "Oui",
      transmission: "Automatique",
      fuel: "Essence",
    },
  ],
  [
    {
      name: "Golf",
      price: "129,50",
      img: CarGolf,
      model: "Golf",
      mark: "Volkswagen",
      year: "2015",
      doors: "4/5",
      air: "Oui",
      transmission: "Manuelle",
      fuel: "Diesel",
    },
  ],
];
